# Generated by Django 5.1 on 2024-08-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(default='firma', max_length=50)),
                ('contactName', models.CharField(default='firma', max_length=50)),
                ('address', models.CharField(default='osoite', max_length=100)),
                ('phone', models.CharField(default='puhelin', max_length=20)),
                ('email', models.CharField(default='sähköposti', max_length=50)),
                ('country', models.CharField(default='maa', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(default='laku', max_length=20)),
                ('packageSize', models.CharField(default=3, max_length=20)),
                ('unitPrice', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('unitsInStock', models.IntegerField(default=3)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier')),
            ],
        ),
    ]
