databases:
  - name: suppliersdb
    plan: free
    databaseName: suppliers
    user: sebab

services:
  - type: web
    plan: free
    name: suppliers
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn suppliers.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: suppliersdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SUPERUSER_USERNAME
        value: "sebab"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "sebab"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "super@usersuper.fi"